version: "2"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  db:
    image: postgis/postgis
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  server:
    # init: true
    build:
      context: .
    environment:
      - VIRTUAL_HOST=poc.meteoschweiz-poc.swisstopo.cloud
      - VIRTUAL_PORT=8484
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=poc.meteoschweiz-poc.swisstopo.cloud
      - RUST_LOG=${RUST_LOG}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - APP_USER=${APP_USER}
      - APP_PASSWORD=${APP_PASSWORD}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - INITIALIZE=${INITIALIZE}
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # - AWS_REGION=${AWS_REGION}
      # - AWS_CUSTOM_ENDPOINT=http://minio:9000
      - SQLX_OFFLINE=true
    command: cargo run
    ports:
      - ${APP_PORT}:${APP_PORT}

  # minio:
  #   image: minio/minio
  #   environment:
  #     - VIRTUAL_HOST=poc.meteoschweiz-poc.swisstopo.cloud
  #     - VIRTUAL_PORT=9000
  #     - VIRTUAL_PATH=/minio/
  #     - VIRTUAL_DEST=/
  #   volumes:
  #     - data:/data
  #   command: server /data
  #   ports:
  #     - 9000:9000
  # createbuckets:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
  #     /usr/bin/mc mb myminio/${AWS_S3_BUCKET_NAME};
  #     /usr/bin/mc policy set public myminio/${AWS_S3_BUCKET_NAME};
  #     /usr/bin/mc admin user add myminio ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY};
  #     /usr/bin/mc admin policy set myminio readwrite user=${AWS_ACCESS_KEY_ID};
  #     exit 0;
  #     "

volumes:
  certs:
  vhost:
  html:
  acme:
  # data:
